---
- name: Genereting consul encrypt
  hosts: web01
  # become: false
  # become_user: consul
  tasks:
    - name: Creating consul.service
      ansible.builtin.template:
        src: templates/consul.service.j2
        dest: /usr/lib/systemd/system/consul.service
        mode: "0755"

    - name: Reloading daemon
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: consul.service

    - name: Starting ACL bootstrap
      ansible.builtin.command:
        cmd: "consul acl bootstrap -format=json | tee /etc/consul.d/certs/bootstrap_token.json"
      changed_when: true

# consul acl bootstrap -format=json | tee /etc/consul.d/certs/bootstrap_token.json
