- name: Update distributive
  hosts: demo
  tasks:
    - name: Updating distributive
      ansible.builtin.yum:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Updateign Debian distributive
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"
