---
- name: Installation packages and creating users with directories
  hosts: demo
  roles:
    - users
    - packages

- name: Starting consul in web01
  hosts: web01
  roles:
    - node1-consul
- name: Starting consul in web01
  hosts: app01
  roles:
    - node2-consul
- name: Starting consul in web01
  hosts: mc01
  roles:
    - node3-consul

- name: Getting consul membsers
  hosts: web01
  tasks:
    - name: Getting consul status from web01
      ansible.builtin.command: consul members
      register: output
      changed_when: true

    - name: Printing output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"

- name: Running Stolon on web01
  hosts: web01
  become: true
  become_user: postgres
  roles:
    - node1-stolon
