---

- name: Updating distributive
  ansible.builtin.yum:
    update_cache: true
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Updateign Debian distributive
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Downloading postgresql
  ansible.builtin.yum:
    name:
      - postgresql-server
    state: present
- name: Installing yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Creating required directories
  ansible.builtin.file:
    path: /root/{{ item }}
    state: directory
    mode: "755"
  loop:
    - consul
    - go
    - stolon


- name: Downloading golang and installing
  ansible.builtin.get_url:
    url: "{{ go_url }}"
    dest: /srv/
    mode: "0750"
  vars:
    go_url: "https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz"

- name: Creating /srv/go direcroty
  ansible.builtin.file:
    path: /srv/go
    state: directory
    mode: "0755"

- name: Unzipping downloaded file
  ansible.builtin.unarchive:
    src: /srv/go{{ version }}.{{ os }}-{{ arch }}.tar.gz
    remote_src: true
    dest: /srv/go
  vars:
    version: 1.6.2
    os: linux
    arch: amd64

- name: Copying the content of go directory
  ansible.builtin.copy:
    src: /srv/go/go/bin/
    dest: /usr/local/bin/
    remote_src: true
    mode: "0755"

- name: Downloading consul
  ansible.builtin.get_url:
    url: "{{ consul_url }}"
    dest: /root/consul
    mode: "0755"
  vars:
    consul_url: "https://github.com/hashicorp/consul-template/archive/refs/tags/v0.37.1.tar.gz"

- name: Unziping Consul archives
  ansible.builtin.unarchive:
    src: /root/consul/consul-template-{{ vesion }}.tar.gz
    dest: /root/
    remote_src: true
  vars:
    vesion: 0.37.1

- name: Copying consul to /usr/local/bin/
  ansible.builtin.copy:
    src: /usr/bin/consul
    dest: /usr/local/bin/
    remote_src: true
    mode: "0755"


- name: Installing stolon from git repository
  ansible.builtin.get_url:
    url: "{{ stolon_url }}"
    dest: /root/
    mode: "0755"
  vars:
    stolon_url: "https://github.com/sorintlab/stolon/releases/download/v0.17.0/stolon-v0.17.0-linux-amd64.tar.gz"

- name: Unziping stolon
  ansible.builtin.unarchive:
    src: /root/stolon-{{ vesion }}-{{ os }}-{{ arch }}.tar.gz
    dest: /root/
    remote_src: true
  vars:
    vesion: v0.17.0
    os: linux
    arch: amd64

- name: Copying the content of go directory
  ansible.builtin.copy:
    src: /root/stolon-{{ vesion }}-{{ os }}-{{ arch }}/bin/
    dest: /usr/local/bin/
    remote_src: true
    mode: "0755"
  vars:
    vesion: v0.17.0
    os: linux
    arch: amd64
...
