- name: Stolon configuration
  vars:
    ip_address_list: ['192.168.121.11', '192.168.121.12', '192.168.121.14']
    cluster_name: stolon-keeper
    store_backend: consul
    store_endpoints: http://127.0.0.1
    store_endpoint_port: 8500
    cluster_uid: ['postgres0', 'postgres1', 'postgres2']
    data_dir: /data/
    pg_su_user: postgres
    pg_repl_user: repl
    pg_su_user_passwd: P@ssw0rd
    pg_repl_user_passwd: P@ssw0rd
    pg_port: 5432
    pg_bin_path: /usr/bin/
    proxy_port: 15432

  block:

    - name: Getting user status
      ansible.builtin.command: whoami
      register: whoami
      changed_when: true

    - name: Printing user status
      ansible.builtin.debug:
        msg: "{{ whoami.stdout }}"

    - name: "Initializing Stolon on node1"
      ansible.builtin.shell: sh /var/lib/pgsql/demo.sh
      changed_when: true
