- name: Creating user consul
  ansible.builtin.user:
    name: smith
    shell: /bin/bash
- name: Creating directory for consul database
  ansible.builtin.file:
    path: "{{ item }}"
    owner: consul
    group: consul
    recurse: true
    mode: "0700"
  loop:
    - /var/lib/consul
    - /etc/consul.d
    - /etc/consul.d/certs

- name: Creating directory for postgresql
  ansible.builtin.file:
    path: /data
    owner: postgres
    group: postgres
    recurse: true
    mode: "0700"
